# Generated by Django 3.2.5 on 2021-07-29 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date',
        ),
        migrations.AddField(
            model_name='address',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 17, 28, 23, 517911)),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
