# Generated by Django 3.2.5 on 2021-07-31 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_information', '0004_alter_address_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 2, 2, 39, 537586)),
        ),
    ]
