# Generated by Django 3.2.5 on 2021-07-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonSchool',
            new_name='UserSchool',
        ),
    ]
