# Generated by Django 3.2.5 on 2021-07-29 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_rename_personschool_userschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userschool',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='userschool',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='userschool',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userschool',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 17, 28, 23, 521911)),
        ),
    ]
