# Generated by Django 3.2.5 on 2021-07-30 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210729_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschool',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 19, 58, 53, 951225)),
        ),
    ]
